### ISSUE TITLE
The program is failing in Step 3 

### ISSUE THREAD

**Issue by belkhadir** [zHaytam/PageRank#2]
<img width="1436" alt="Screenshot 2019-06-05 at 1 59 43 PM" src="https://user-images.githubusercontent.com/5060683/58962250-54dd1880-879a-11e9-9fce-0cebb0f488e7.png">

**Comment by zHaytam** [comment]
The error is pretty self-explanatory `File /input/pagerank_data.txt does not exist`.
Make sure to put the dataset in HDFS to match that path :')

**Comment by belkhadir** [comment]
<img width="1440" alt="Screenshot 2019-06-05 at 3 58 06 PM" src="https://user-images.githubusercontent.com/5060683/58971337-c1601380-87aa-11e9-89fd-a7b5074e1346.png">
it's in the right path, I'm I doing something wrong ?

**Comment by zHaytam** [comment]
What's the command you're using to run the job?

**Comment by belkhadir** [comment]
hadoop jar File.jar PageRank /input /output /input/pagerank_data.txt 0.85 5 0.01 true true
